### ISSUE TITLE
crash with 1.19.3

### ISSUE THREAD

**Issue by litoj** [Andrew6rant/InventoryTabs#78]
when attempting to save settings it crashes with the same error many other mods get in this weird update:
```log
Caused by: java.lang.NoSuchFieldError: field_11146
	at com.kqp.inventorytabs.api.TabProviderRegistry.init(TabProviderRegistry.java:60) ~[inventorytabs-0.9.beta-1.19.x.jar:?]
	at com.kqp.inventorytabs.init.InventoryTabs.lambda$onInitialize$0(InventoryTabs.java:30) ~[inventorytabs-0.9.beta-1.19.x.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.save(ConfigManager.java:75) ~[cloth-config-9.0.94-fabric.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.save(AbstractConfigScreen.java:182) ~[cloth-config-9.0.94-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.save(ClothConfigScreen.java:322) ~[cloth-config-9.0.94-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:172) ~[cloth-config-9.0.94-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.lambda$init$3(ClothConfigScreen.java:132) ~[cloth-config-9.0.94-fabric.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:263) ~[cloth-config-9.0.94-fabric.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	... 24 more
```

**Comment by dhyces** [comment]
current version of inventory tabs, 1.19.'x'-0.9.beta, is broken with 1.19.3 due to registry changes

**Comment by litoj** [comment]
Is it a simple fix?

**Comment by dhyces** [comment]
it's pretty much just changing some names, so yeah

**Comment by Robben-BRK** [comment]
and what should be changed? I have the same issue as JosefLitos

**Comment by litoj** [comment]
PR #80 updated the mod to be compatible with 1.19.3.

![image](https://user-images.githubusercontent.com/54900518/210226989-81dfc323-646c-4bdf-bd9c-67a3e644d1ef.png)
I am using this version now and everything works fine for me. Do you use the same version @Robben-BRK ?
