### ISSUE TITLE
Minecraft fabric 1.19.3 crashed

### ISSUE THREAD

**Issue by DeQuinn15** [Andrew6rant/InventoryTabs#81]
---- Minecraft Crash Report ----
// You're mean.

Time: 2022-12-27 11:47:03
Description: Load world

java.lang.NoSuchFieldError: field_11146
	at com.kqp.inventorytabs.api.TabProviderRegistry.init(TabProviderRegistry.java:59)
	at com.kqp.inventorytabs.init.InventoryTabs.lambda$onInitialize$1(InventoryTabs.java:33)
	at net.fabricmc.fabric.api.client.networking.v1.ClientLoginConnectionEvents.lambda$static$0(ClientLoginConnectionEvents.java:42)
	at net.fabricmc.fabric.impl.networking.client.ClientLoginNetworkAddon.<init>(ClientLoginNetworkAddon.java:55)
	at net.minecraft.class_635.handler$zhn002$initAddon(class_635.java:549)
	at net.minecraft.class_635.<init>(class_635.java:65)
	at net.minecraft.class_310.method_29610(class_310.java:2119)
	at net.minecraft.class_7196.method_43326(class_7196.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:222)
	at net.minecraft.class_7196.method_41897(class_7196.java:209)
	at net.minecraft.class_7196.method_41896(class_7196.java:275)
	at net.minecraft.class_405.method_19792(class_405.java:36)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215)
	at net.minecraft.class_310.method_1523(class_310.java:1225)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kqp.inventorytabs.api.TabProviderRegistry.init(TabProviderRegistry.java:59)
	at com.kqp.inventorytabs.init.InventoryTabs.lambda$onInitialize$1(InventoryTabs.java:33)
	at net.fabricmc.fabric.api.client.networking.v1.ClientLoginConnectionEvents.lambda$static$0(ClientLoginConnectionEvents.java:42)
	at net.fabricmc.fabric.impl.networking.client.ClientLoginNetworkAddon.<init>(ClientLoginNetworkAddon.java:55)
	at net.minecraft.class_635.handler$zhn002$initAddon(class_635.java:549)
	at net.minecraft.class_635.<init>(class_635.java:65)
	at net.minecraft.class_310.method_29610(class_310.java:2119)
	at net.minecraft.class_7196.method_43326(class_7196.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:222)
	at net.minecraft.class_7196.method_41897(class_7196.java:209)
	at net.minecraft.class_7196.method_41896(class_7196.java:275)
	at net.minecraft.class_405.method_19792(class_405.java:36)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/Fullbright 1.19.2 - UB.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_43589(class_310.java:874)
	at net.minecraft.class_310.method_1514(class_310.java:770)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 688086704 bytes (656 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x0fc6
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6192
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18117.18
	Virtual memory used (MB): 12953.07
	Swap memory total (MB): 1790.75
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: Cloth Config v9 9.0.93
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 5.45
			fiber: fiber 0.23.0-2
		fabric-api: Fabric API 0.69.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7185
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea85
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e85
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.12+49abcf7e85
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.1+112a38be85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.39+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df85
			fabric-item-api-v1: Fabric Item API (v1) 2.1.5+4d2c606385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.8+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.18+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.22+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.29+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3985
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.0+e9dee00485
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46385
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.3+a10d22bd85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.39+1d4d0b5785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7185
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.12+82a2701785
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b85
		fabricloader: Fabric Loader 0.14.12
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.13.0
		malilib: MaLiLib 0.14.0
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.0.2
		mousewheelie: Mouse Wheelie 1.10.6+mc1.19.3
			amecsapi: Amecs API 1.3.6+mc1.19.3
			coat: Coat 1.0.0-beta.19+mc1.19.3
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.19.3
			tweed4_base: tweed4_base 1.7.1+mc1.19.3
			tweed4_data: tweed4_data 1.2.1+mc1.19.3
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.19.3
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.19.3
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc1.19.3
		phosphor: Phosphor 0.8.1
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3
		sodium: Sodium 0.4.6+build.20
		terralith: Terralith 2.3
		wi_zoom: WI Zoom 1.4-MC1.19.3
		xaerobetterpvp: Better PVP Mod 22.17.0
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GTX 650/PCIe/SSE2 GL version 3.2.0 NVIDIA 461.92, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Fullbright 1.19.2 - UB.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by leon0399** [comment]
Duplicate, see #78

**Comment by litoj** [comment]
Please close this as it is a duplicate.
